### ISSUE TITLE
Validate catalog-info.yaml

### ISSUE THREAD

**Issue by zrob** [sample-accelerators/tap-initialize#1]
Validate content with folks that know more about components 

Open questions:
- [x] Is the current skeleton missing any info that should be included for best practices?
- [x] Where should the file be placed? (currently ends up in `catalog/catalog-info.yaml`)
- [x] Is `spec.type` the correct default value? (currently `service`)
- [x] Is `spec.lifecycle` the correct default value? (currently `experimental`)
- [x] Is `spec.owner` the correct default value? (currently `default-owner`)

**Comment by krisapplegate** [comment]
1. Looks good
2. catalog/catalog-info.yaml makes sense. However, you're the only team delivering that, so it's not etched in stone. However the filename itself 'catalog-info.yaml' I would keep the same regardless of folders.
3. spec.type looks good
4. spec.lifecycle is up to you. I'd be more inclined for something like developmental as opposed to experimental.
5. spec.owner I would set to guest so that it's viewable by most people upon login

**Comment by zrob** [comment]
thanks so much for the review @krisapplegate !

Will update the spec.owner property.

for lifecycle, it looks like any text is valid, but the docs recommend a specific list of "well known" values
https://backstage.io/docs/features/software-catalog/descriptor-format#speclifecycle-required-1 that i suppose we should fall into line with
